language: python
python:
  - 2.7
  - 3.4

env:
  - DJANGO="django<1.8"
  - DJANGO="django<1.9"
  - DJANGO="django==1.9"

install:
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - cd example/ && ./manage.py test testapp --settings=testapp.settings
